const PERMISSIONS = {
  'space:create': ['admin', 'location_manager'],
  'space:update': ['admin', 'location_manager'],
  'space:delete': ['admin'],
  'space:view': ['admin', 'location_manager', 'member', 'guest'],
  'space:availability': ['admin', 'location_manager', 'member', 'guest'],
  'booking:create': ['admin', 'location_manager', 'member'],
  'booking:cancel_own': ['admin', 'location_manager', 'member'],
  'booking:cancel_any': ['admin', 'location_manager'],
  'booking:view_own': ['admin', 'location_manager', 'member', 'guest'],
  'booking:view_all': ['admin', 'location_manager'],
  'booking:checkin': ['admin', 'location_manager', 'member', 'guest'],
  'booking:checkout': ['admin', 'location_manager', 'member', 'guest'],
  'location:create': ['admin'],
  'location:update': ['admin', 'location_manager'],
  'location:delete': ['admin'],
  'location:view': ['admin', 'location_manager', 'member', 'guest'],
  'location:assign_manager': ['admin'],
  'billing:view_own': ['admin', 'location_manager', 'member'],
  'billing:view_all': ['admin', 'location_manager'],
  'guestpass:create': ['admin', 'location_manager', 'member'],
  'guestpass:revoke': ['admin', 'location_manager', 'member'],
  'guestpass:view': ['admin', 'location_manager', 'member'],
  'review:create': ['admin', 'location_manager', 'member'],
  'review:delete_own': ['admin', 'location_manager', 'member'],
  'review:delete_any': ['admin'],
  'review:view': ['admin', 'location_manager', 'member', 'guest'],
  'user:manage': ['admin'],
  'user:view_location': ['admin', 'location_manager'],
};

module.exports = PERMISSIONS;
